alter table CAMPAIGN_BANNER_POSITION add constraint FK_CAMPAIGN_BANNER_POSITION_WEBSITE foreign key (WEBSITE_ID) references CAMPAIGN_WEBSITE(ID);
create index IDX_CAMPAIGN_BANNER_POSITION_WEBSITE on CAMPAIGN_BANNER_POSITION (WEBSITE_ID);
