alter table CAMPAIGN_CAMPAIGN_BANNER_POSITION add column DAILY_IMPRESSIONS integer ^
update CAMPAIGN_CAMPAIGN_BANNER_POSITION set DAILY_IMPRESSIONS = 0 where DAILY_IMPRESSIONS is null ;
alter table CAMPAIGN_CAMPAIGN_BANNER_POSITION alter column DAILY_IMPRESSIONS set not null ;
alter table CAMPAIGN_CAMPAIGN_BANNER_POSITION drop column IMPRESSIONS cascade ;
