alter table SALESNEW_ORDER add constraint FK_SALESNEW_ORDER_CUSTOMER foreign key (CUSTOMER_ID) references SALESNEW_CUSTOMER(ID);
create index IDX_SALESNEW_ORDER_CUSTOMER on SALESNEW_ORDER (CUSTOMER_ID);
