-- begin SALESNEW_ORDER
alter table SALESNEW_ORDER add constraint FK_SALESNEW_ORDER_CUSTOMER foreign key (CUSTOMER_ID) references SALESNEW_CUSTOMER(ID)^
create index IDX_SALESNEW_ORDER_CUSTOMER on SALESNEW_ORDER (CUSTOMER_ID)^
-- end SALESNEW_ORDER
-- begin SALESNEW_ODER_LINE
alter table SALESNEW_ODER_LINE add constraint FK_SALESNEW_ODER_LINE_ORDER foreign key (ORDER_ID) references SALESNEW_ORDER(ID)^
alter table SALESNEW_ODER_LINE add constraint FK_SALESNEW_ODER_LINE_PRODUCT foreign key (PRODUCT_ID) references SALESNEW_PRODUCT(ID)^
create index IDX_SALESNEW_ODER_LINE_ORDER on SALESNEW_ODER_LINE (ORDER_ID)^
create index IDX_SALESNEW_ODER_LINE_PRODUCT on SALESNEW_ODER_LINE (PRODUCT_ID)^
-- end SALESNEW_ODER_LINE
